Repository terraform-providers/terraform-provider-pureport, pull requests merged in 2020-08, with the labels that each got.

#8 adds support for customer_asn to pureport_aws_connection
  pureport/resource_pureport_aws_connection.go
  website/docs/r/aws_connection.html.md
Labels: documentation, size/XS

#9 Increase Travis timeout for running Code Lint
  .travis.yml
  Jenkinsfile
Labels: bug, size/XS

#10 Update changelog
  CHANGELOG.md
Labels: size/XS
